name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:debian-12-ocaml-5.1
      options: --user=opam

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo chown -R opam:opam .
        eval $(opam env)
        opam install dune core ounit2

    - name: Build
      run: |
        eval $(opam env)
        dune build

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest
