name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: 5.1.0

    - name: Install dependencies
      run: |
        opam install dune core ounit2

    - name: Build project
      run: dune build

    - name: Run tests
      run: dune runtest
