name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.1.0
        disable-sudo: true

    - name: Install dependencies
      run: |
        opam install dune core ounit2

    - name: Build the project
      run: dune build

    - name: Run tests
      run: dune runtest
