name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:debian-12-ocaml-5.1
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up permissions
      run: chown -R opam:opam .

    - name: Install dependencies
      run: |
        su opam -c 'eval $(opam env) && opam install dune core ounit2'

    - name: Build
      run: |
        su opam -c 'eval $(opam env) && dune build'

    - name: Run tests
      run: |
        su opam -c 'eval $(opam env) && dune runtest'
